name: Word Count
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  update-readme-with-word-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count Words
        run: |
          WORD_COUNT=$(grep -o '\w*' README.md | wc -w)
          sed -i "3s/.*/Word Count: $WORD_COUNT/" README.md
      - name: Commit Changes
        run: |
          git config --local user.email "wordcount@bot.com"
          git config --local user.name "Word Count Bot"
          git add README.md
          git commit -m "Bot updated word count" && echo ::set-output name=commit::true || echo ::set-output name=commit::false
      - name: Push Changes
        if: steps.commit.outputs.commit == 'true'
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
